version: 2
jobs:
  jc:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello "
  pam:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Double trouble "
workflows:
  version: 2
  jc_pam:
    jobs:
      - jc
      - pam